name: Publish on GitHub, CurseForge & Modrinth

on: [ pull_request, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.21.10
  JAVA_VERSION: 21

permissions:
  contents: write

jobs:
  build:
    permissions:
      contents: write
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: AANobbMI
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 394468
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on GitHub.
          github-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}